import type { AdminListing } from "./types";

const cover = (id: number) => `/images/books/book${id}.jpg`;

export const mockAdminListings: AdminListing[] = [
  {
    id: "LST-24081",
    title: "Calculus: Early Transcendentals",
    author: "James Stewart",
    isbn: "9781285741550",
    edition: "8th",
    coverImageUrl: cover(1),
    imageUrls: [cover(1), cover(2), cover(3)],
    listingType: "sale",
    priceAmountMinor: 3200,
    currencyCode: "USD",
    condition: "good",
    country: "United States",
    city: "Boston",
    category: "Textbook",
    educationLevel: "University",
    grade: "Undergraduate",
    schoolType: "not_applicable",
    schoolName: null,
    subject: "Mathematics",
    language: "English",
    sellerId: "USR-1042",
    sellerName: "Nadine Ifguisse",
    sellerType: "private_user",
    sellerVerified: true,
    listingStatus: "active",
    moderationStatus: "normal",
    riskLevel: "normal",
    reportsCount: 0,
    viewsCount: 318,
    favoritesCount: 24,
    reservationRequestsCount: 5,
    duplicateStatus: "not_checked",
    safetyFlags: [],
    description:
      "Clean copy with highlighted derivative chapters. Pickup near campus or tracked shipping.",
    deliveryOptions: ["Pickup", "Tracked shipping"],
    reports: [],
    moderationHistory: [
      {
        id: "MOD-501",
        date: "2026-06-05T10:12:00.000Z",
        moderator: "System",
        action: "Listing published",
        reason: "Seller submitted listing",
        internalNote: "No automatic safety flags.",
        previousStatus: "draft",
        newStatus: "active",
      },
    ],
    createdAt: "2026-06-05T10:12:00.000Z",
    updatedAt: "2026-06-07T16:42:00.000Z",
  },
  {
    id: "LST-24077",
    title: "Organic Chemistry",
    author: "Paula Yurkanis Bruice",
    isbn: "9780134042282",
    edition: "7th",
    coverImageUrl: cover(4),
    imageUrls: [cover(4)],
    listingType: "swap",
    priceAmountMinor: null,
    currencyCode: "USD",
    condition: "fair",
    country: "Morocco",
    city: "Casablanca",
    category: "Textbook",
    educationLevel: "University",
    grade: "Undergraduate",
    schoolType: "not_applicable",
    schoolName: null,
    subject: "Chemistry",
    language: "English",
    sellerId: "USR-1041",
    sellerName: "Youssef El Mansouri",
    sellerType: "bookstore",
    sellerVerified: true,
    listingStatus: "active",
    moderationStatus: "reported",
    riskLevel: "medium_risk",
    reportsCount: 2,
    viewsCount: 201,
    favoritesCount: 18,
    reservationRequestsCount: 3,
    duplicateStatus: "possible_duplicate",
    safetyFlags: [
      {
        id: "FLG-144",
        ruleId: "duplicate_content",
        label: "Possible duplicate description",
        snippet: "Same edition and description seen in another active listing.",
        createdAt: "2026-06-06T09:04:00.000Z",
      },
    ],
    description:
      "Looking to swap for a physics textbook. Same description appears across two bookstore listings.",
    deliveryOptions: ["Pickup"],
    reports: [
      {
        id: "RPT-2291",
        reporter: "Camille Dubois",
        reason: "duplicate_listing",
        description: "I found the same listing posted twice.",
        createdAt: "2026-06-06T12:18:00.000Z",
        status: "open",
        assignedModerator: "Unassigned",
        resolution: "",
      },
      {
        id: "RPT-2298",
        reporter: "Jonas Richter",
        reason: "misleading_description",
        description: "Condition may be worse than shown.",
        createdAt: "2026-06-07T18:20:00.000Z",
        status: "under_review",
        assignedModerator: "Mina Rahal",
        resolution: "",
      },
    ],
    moderationHistory: [
      {
        id: "MOD-494",
        date: "2026-06-06T09:04:00.000Z",
        moderator: "System",
        action: "Duplicate flag created",
        reason: "duplicate_content",
        internalNote: "Needs moderator review before removal.",
        previousStatus: "normal",
        newStatus: "reported",
      },
    ],
    createdAt: "2026-06-04T14:25:00.000Z",
    updatedAt: "2026-06-07T18:20:00.000Z",
  },
  {
    id: "LST-24070",
    title: "Harry Potter and the Prisoner of Azkaban",
    author: "J. K. Rowling",
    isbn: "9780439136365",
    edition: "Paperback",
    coverImageUrl: cover(6),
    imageUrls: [cover(6), cover(7)],
    listingType: "giveaway",
    priceAmountMinor: null,
    currencyCode: "EUR",
    condition: "likenew",
    country: "France",
    city: "Lyon",
    category: "Fiction",
    educationLevel: "not_applicable",
    grade: "not_applicable",
    schoolType: "not_applicable",
    schoolName: null,
    subject: "Literature",
    language: "English",
    sellerId: "USR-1038",
    sellerName: "Camille Dubois",
    sellerType: "private_user",
    sellerVerified: true,
    listingStatus: "reserved",
    moderationStatus: "normal",
    riskLevel: "normal",
    reportsCount: 0,
    viewsCount: 452,
    favoritesCount: 41,
    reservationRequestsCount: 12,
    duplicateStatus: "not_checked",
    safetyFlags: [],
    description: "Free pickup this week. Includes dust jacket and no missing pages.",
    deliveryOptions: ["Pickup"],
    reports: [],
    moderationHistory: [
      {
        id: "MOD-486",
        date: "2026-06-03T08:11:00.000Z",
        moderator: "System",
        action: "Listing reserved",
        reason: "Giveaway request accepted",
        internalNote: "Conflicting requests blocked.",
        previousStatus: "active",
        newStatus: "reserved",
      },
    ],
    createdAt: "2026-06-01T08:11:00.000Z",
    updatedAt: "2026-06-03T08:11:00.000Z",
  },
  {
    id: "LST-24051",
    title: "Business Statistics",
    author: "Ken Black",
    isbn: "9781119290142",
    edition: "9th",
    coverImageUrl: null,
    imageUrls: [],
    listingType: "sale",
    priceAmountMinor: 8500,
    currencyCode: "EUR",
    condition: "likenew",
    country: "Belgium",
    city: "Brussels",
    category: "Textbook",
    educationLevel: "University",
    grade: "Graduate",
    schoolType: "private_school",
    schoolName: "Brussels Business School",
    subject: "Business",
    language: "English",
    sellerId: "USR-1031",
    sellerName: "Mina Rahal",
    sellerType: "pro_seller",
    sellerVerified: false,
    listingStatus: "hidden",
    moderationStatus: "under_review",
    riskLevel: "high_risk",
    reportsCount: 5,
    viewsCount: 719,
    favoritesCount: 3,
    reservationRequestsCount: 1,
    duplicateStatus: "confirmed_duplicate",
    safetyFlags: [
      {
        id: "FLG-151",
        ruleId: "external_payment_request",
        label: "External payment language",
        snippet: "Seller asks buyers to pay by bank transfer before shipping.",
        createdAt: "2026-06-02T19:18:00.000Z",
      },
      {
        id: "FLG-152",
        ruleId: "price_outlier",
        label: "Price outlier",
        snippet: "Price is far above comparable copies in this condition.",
        createdAt: "2026-06-02T19:19:00.000Z",
      },
    ],
    description:
      "Brand new. Message me for payment by bank transfer. Faster outside the platform.",
    deliveryOptions: ["Shipping"],
    reports: [
      {
        id: "RPT-2280",
        reporter: "Ari Cohen",
        reason: "external_payment_pressure",
        description: "Seller pushed payment outside BookSwap.",
        createdAt: "2026-06-02T20:13:00.000Z",
        status: "open",
        assignedModerator: "Sofia Alvarez",
        resolution: "",
      },
    ],
    moderationHistory: [
      {
        id: "MOD-478",
        date: "2026-06-02T19:21:00.000Z",
        moderator: "Sofia Alvarez",
        action: "Listing hidden",
        reason: "external_payment_request",
        internalNote: "Soft-hidden pending seller response.",
        previousStatus: "active",
        newStatus: "hidden",
      },
    ],
    createdAt: "2026-05-30T19:18:00.000Z",
    updatedAt: "2026-06-02T20:13:00.000Z",
  },
  {
    id: "LST-23994",
    title: "Spanish Grammar in Context",
    author: "Juan Kattan-Ibarra",
    isbn: "9781138775955",
    edition: "3rd",
    coverImageUrl: cover(9),
    imageUrls: [cover(9)],
    listingType: "swap",
    priceAmountMinor: null,
    currencyCode: "GBP",
    condition: "poor",
    country: "United Kingdom",
    city: "London",
    category: "Language learning",
    educationLevel: "Secondary",
    grade: "Grade 12",
    schoolType: "public_school",
    schoolName: "North London Sixth Form",
    subject: "Spanish",
    language: "Spanish",
    sellerId: "USR-1008",
    sellerName: "Ari Cohen",
    sellerType: "private_user",
    sellerVerified: false,
    listingStatus: "removed",
    moderationStatus: "removed",
    riskLevel: "high_risk",
    reportsCount: 11,
    viewsCount: 880,
    favoritesCount: 2,
    reservationRequestsCount: 0,
    duplicateStatus: "not_checked",
    safetyFlags: [
      {
        id: "FLG-180",
        ruleId: "reported_multiple_times",
        label: "Reported multiple times",
        snippet: "Repeated reports mention missing pages not disclosed.",
        createdAt: "2026-05-31T11:18:00.000Z",
      },
    ],
    description: "Damaged language book. Some exercises removed.",
    deliveryOptions: ["Pickup", "Shipping"],
    reports: [
      {
        id: "RPT-2214",
        reporter: "Lea Martin",
        reason: "missing_pages_not_disclosed",
        description: "Several pages are missing from the workbook.",
        createdAt: "2026-05-31T11:17:00.000Z",
        status: "resolved",
        assignedModerator: "Sofia Alvarez",
        resolution: "Removed after seller failed to update description.",
      },
    ],
    moderationHistory: [
      {
        id: "MOD-455",
        date: "2026-05-31T13:40:00.000Z",
        moderator: "Sofia Alvarez",
        action: "Listing removed",
        reason: "missing_pages_not_disclosed",
        internalNote: "Soft deletion only. Seller notified.",
        previousStatus: "hidden",
        newStatus: "removed",
      },
    ],
    createdAt: "2026-05-25T07:44:00.000Z",
    updatedAt: "2026-05-31T13:40:00.000Z",
  },
  {
    id: "LST-23981",
    title: "Le Petit Prince",
    author: "Antoine de Saint-Exupery",
    isbn: "9782070612758",
    edition: "Folio",
    coverImageUrl: cover(12),
    imageUrls: [cover(12), cover(11)],
    listingType: "sale",
    priceAmountMinor: 700,
    currencyCode: "EUR",
    condition: "likenew",
    country: "France",
    city: "Marseille",
    category: "Fiction",
    educationLevel: "not_applicable",
    grade: "not_applicable",
    schoolType: "not_applicable",
    schoolName: null,
    subject: "Literature",
    language: "French",
    sellerId: "USR-997",
    sellerName: "Lea Martin",
    sellerType: "private_user",
    sellerVerified: false,
    listingStatus: "draft",
    moderationStatus: "normal",
    riskLevel: "normal",
    reportsCount: 0,
    viewsCount: 0,
    favoritesCount: 0,
    reservationRequestsCount: 0,
    duplicateStatus: "allowed_multiple_quantity",
    safetyFlags: [],
    description: "Draft created by seller. Not visible to marketplace buyers yet.",
    deliveryOptions: ["Pickup"],
    reports: [],
    moderationHistory: [
      {
        id: "MOD-440",
        date: "2026-05-21T09:30:00.000Z",
        moderator: "System",
        action: "Draft created",
        reason: "Seller started listing",
        internalNote: "Awaiting publication.",
        previousStatus: "draft",
        newStatus: "draft",
      },
    ],
    createdAt: "2026-05-21T09:30:00.000Z",
    updatedAt: "2026-05-21T09:30:00.000Z",
  },
];

export function getMockAdminListings() {
  return mockAdminListings;
}

export function getMockAdminListing(listingId: string) {
  return mockAdminListings.find((listing) => listing.id === listingId) ?? null;
}
